---
# tasks file for apache_download
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: true

- name: Check if port 80 is open
  wait_for:
    host: localhost
    port: 80
    state: started
  become: true

- name: Check if Apache is running
  command: systemctl status apache2 
  ignore_errors: yes
  changed_when: false
  register: service_apache_status